name: learn-github-actions

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v6
        env:
          RUN_LOCAL: true
